### ISSUE TITLE
How can i install this?

### ISSUE THREAD

**Issue by vgisuruex** [John10v10/BFRES-Editor-for-Blender#1]
i tried installing this by selecting the zip and the py but none of them worked. i tired putting it manually but still no luck. how can i install it?

**Comment by John10v10** [comment]
Hi vgisuruex,

All you need to do is download the script alone, and open it in Blender's text editor, then click "Run Script."

Does that work for you?

**Comment by vgisuruex** [comment]
when i click run script, nothing happens

**Comment by John10v10** [comment]
So, even after you click "Run Script", you still cannot see the BFRES tab?

![image](https://user-images.githubusercontent.com/16232480/56631665-e6922b80-661b-11e9-8c46-d8c90d7e6c9f.png)

**Comment by vgisuruex** [comment]
didn't notice that, it works now! thank you very much.
